# Site settings
title: The Lecture List
description: >-
  A curated archive of public lectures from across the UK (2003-2018).
  Discover talks on science, arts, politics, and more from leading thinkers.
baseurl: "/LL-2025" # GitHub Pages project site
url: "https://lrdj.github.io" # GitHub Pages URL

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  lectures:
    output: true
    permalink: /lectures/:slug/
  speakers:
    output: true
    permalink: /speakers/:slug/
  topics:
    output: true
    permalink: /topics/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "lectures"
    values:
      layout: "lecture"
  - scope:
      path: ""
      type: "speakers"
    values:
      layout: "speaker"
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"

# Pagination
paginate: 20
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - README.md

# Include
include:
  - _pages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
twitter:
  username: lecturelist
  card: summary

social:
  name: The Lecture List
  links:
    - https://twitter.com/lecturelist

# Site navigation
navigation:
  - title: Browse
    url: /browse/
  - title: Topics
    url: /topics/
  - title: Speakers
    url: /speakers/
  - title: About
    url: /about/

